### ISSUE TITLE
Image encodings and text encodings are not same

### ISSUE THREAD

**Issue by m-ali-awan** [SBMagar/VQGAN-CLIP-Text-to-Image#2]
First of all thanks for such a wonderful blog.
But I have some reservations/confusions as compared to dribnet official implementation.
Particularly I am facing the following error:
```
RuntimeError: cosine_similarity requires both inputs to have the same sizes, but x1 has [1, 512] and x2 has [32, 512]

```
in the optimizeResult function here:
```
main_loss = torch.cosine_similarity(final_text_include_enc, image_enc, -1) # 32
```

Thanks again.

**Comment by sbmagar13** [comment]
I couldn't get it, can you please show(share the codes) more in detail?

In the case of image_enc there are 32 crops with a dimensionality of 512, But in the case of text-include-enc there is just 1 with a dimensionality of 512....  (which is later normalized for the correct range value) 
During the calculation of loss, each encoding of all 32 crops image should be compared with a single encoding(mathematical vector) of text ... So, it will produce 32 crops with a dimensionality of 512...

**Comment by m-ali-awan** [comment]
Hi @SBMagar, thanks for reaching back. I solved it by using repeat, as here:
```
final_text_enc=final_text_enc.repeat(32,1)
```

**Comment by m-ali-awan** [comment]
Moreover, the links for downloading models are also not working, so I used from nerdyrodent's VQGAN-CLIP repo.

**Comment by sbmagar13** [comment]
Cool, and, Thank you so much for reading my blog... :)

**Comment by sbmagar13** [comment]
And that was really great!!!

**Comment by sbmagar13** [comment]
For now, I'm closing the issue

**Comment by m-ali-awan** [comment]
Thanks again, for your great content. Hope to stay in touch.
Take care.

**Comment by sbmagar13** [comment]
Definitely... Take care you too.
